import { ScenarioTemplate } from "../types";

export const HIGH_FREQUENCY_TEMPLATE_TITLES = [
  "这活不归我，怎么说",
  "同事把责任推给我，怎么澄清",
  "亲戚催婚，怎么结束话题",
  "高铁换座，怎么礼貌拒绝",
  "朋友借钱，怎么拒绝",
  "不想参加聚会，怎么说",
];

export const FALLBACK_TEMPLATES: ScenarioTemplate[] = [
  {
    id: "local-1",
    template_code: "work_not_my_job",
    category_level_1: "职场",
    category_level_2: "职责边界",
    title: "这活不归我，怎么说",
    short_desc: "明确职责边界，避免默认接活。",
    preset_input: "同事总把不属于我的工作交给我，我不想再默认接了。",
    recommended_tones: ["礼貌委婉", "坚定直接", "留痕确认"],
    priority: 100,
    status: "enabled",
    sort_order: 1,
  },
  {
    id: "local-2",
    template_code: "work_tmp_dump",
    category_level_1: "职场",
    category_level_2: "临时甩活",
    title: "同事临时甩活，怎么拒绝",
    short_desc: "拒绝临时甩活，同时给出协作边界。",
    preset_input: "同事临时把工作甩给我，但这件事不在我负责范围内。",
    recommended_tones: ["礼貌委婉", "坚定直接", "简短边界"],
    priority: 90,
    status: "enabled",
    sort_order: 2,
  },
  {
    id: "local-3",
    template_code: "work_overtime_assign",
    category_level_1: "职场",
    category_level_2: "下班后安排",
    title: "下班后临时安排工作，怎么回",
    short_desc: "表达时间边界，避免被无限加班。",
    preset_input: "下班后突然安排工作，我今晚不方便继续处理。",
    recommended_tones: ["礼貌委婉", "温和留余地", "简短边界"],
    priority: 80,
    status: "enabled",
    sort_order: 3,
  },
  {
    id: "local-4",
    template_code: "work_trace_confirm",
    category_level_1: "职场",
    category_level_2: "留痕确认",
    title: "担心被甩锅，先留痕确认",
    short_desc: "先确认责任边界，减少后续扯皮。",
    preset_input: "这项工作责任边界不清，我担心后续被甩锅。",
    recommended_tones: ["留痕确认", "坚定直接", "礼貌委婉"],
    priority: 88,
    status: "enabled",
    sort_order: 4,
  },
  {
    id: "local-5",
    template_code: "work_blame_shift",
    category_level_1: "职场",
    category_level_2: "责任澄清",
    title: "同事把责任推给我，怎么澄清",
    short_desc: "聚焦事实澄清，避免情绪化争执。",
    preset_input: "同事在会上把问题责任推到我身上，我想明确澄清。",
    recommended_tones: ["坚定直接", "留痕确认", "礼貌委婉"],
    priority: 95,
    status: "enabled",
    sort_order: 5,
  },
  {
    id: "local-6",
    template_code: "work_passive_aggressive",
    category_level_1: "职场",
    category_level_2: "阴阳甩锅",
    title: "领导面前被阴阳甩锅，怎么回",
    short_desc: "保持冷静，回到分工事实。",
    preset_input: "同事在领导面前阴阳我、暗示是我的问题，我想当场回应。",
    recommended_tones: ["坚定直接", "留痕确认", "简短边界"],
    priority: 78,
    status: "enabled",
    sort_order: 6,
  },
  {
    id: "local-7",
    template_code: "family_marriage_push",
    category_level_1: "家庭",
    category_level_2: "催婚",
    title: "亲戚催婚，怎么结束话题",
    short_desc: "不解释过多，礼貌结束催婚对话。",
    preset_input: "亲戚又在催婚，我不想每次都解释自己的打算。",
    recommended_tones: ["礼貌委婉", "简短边界", "温和留余地"],
    priority: 92,
    status: "enabled",
    sort_order: 7,
  },
  {
    id: "local-8",
    template_code: "family_private_questions",
    category_level_1: "家庭",
    category_level_2: "隐私追问",
    title: "被问对象、收入、私生活，怎么挡回去",
    short_desc: "保护隐私，不做无效解释。",
    preset_input: "家里聚会总被追问收入和感情情况，我不想回答这些。",
    recommended_tones: ["简短边界", "礼貌委婉", "坚定直接"],
    priority: 76,
    status: "enabled",
    sort_order: 8,
  },
  {
    id: "local-9",
    template_code: "family_make_decision",
    category_level_1: "家庭",
    category_level_2: "替我决定",
    title: "家里人替我做决定，怎么表达不同意",
    short_desc: "平和但明确表达自己的决定权。",
    preset_input: "家里人替我安排了事情，但我并不同意这个决定。",
    recommended_tones: ["温和留余地", "坚定直接", "礼貌委婉"],
    priority: 74,
    status: "enabled",
    sort_order: 9,
  },
  {
    id: "local-10",
    template_code: "friend_borrow_money",
    category_level_1: "熟人请求",
    category_level_2: "借钱",
    title: "朋友借钱，怎么拒绝",
    short_desc: "拒绝借钱且不撕破关系。",
    preset_input: "朋友来借钱，但我不想借也不想伤和气。",
    recommended_tones: ["礼貌委婉", "简短边界", "坚定直接"],
    priority: 93,
    status: "enabled",
    sort_order: 10,
  },
  {
    id: "local-11",
    template_code: "friend_free_help",
    category_level_1: "熟人请求",
    category_level_2: "免费帮忙",
    title: "找我免费帮忙，怎么回绝",
    short_desc: "表达专业边界，避免被长期消耗。",
    preset_input: "熟人总找我免费帮忙，我想拒绝但不想太硬。",
    recommended_tones: ["礼貌委婉", "坚定直接", "简短边界"],
    priority: 72,
    status: "enabled",
    sort_order: 11,
  },
  {
    id: "local-12",
    template_code: "friend_resource_intro",
    category_level_1: "熟人请求",
    category_level_2: "介绍资源",
    title: "让我介绍资源、人脉，怎么婉拒",
    short_desc: "不背书、不承诺，守住资源边界。",
    preset_input: "有人让我介绍人脉资源，但我不想介入。",
    recommended_tones: ["礼貌委婉", "温和留余地", "简短边界"],
    priority: 70,
    status: "enabled",
    sort_order: 12,
  },
  {
    id: "local-13",
    template_code: "social_party_decline",
    category_level_1: "社交",
    category_level_2: "聚会拒绝",
    title: "不想参加聚会，怎么说",
    short_desc: "简洁拒绝，不拖泥带水。",
    preset_input: "朋友约聚会，但我不想参加也不想反复解释。",
    recommended_tones: ["礼貌委婉", "简短边界", "温和留余地"],
    priority: 91,
    status: "enabled",
    sort_order: 13,
  },
  {
    id: "local-14",
    template_code: "social_end_chat",
    category_level_1: "社交",
    category_level_2: "结束聊天",
    title: "不想继续聊天，怎么收尾",
    short_desc: "明确结束对话，不制造误解。",
    preset_input: "这个聊天我不想继续了，但想体面收尾。",
    recommended_tones: ["简短边界", "礼貌委婉", "坚定直接"],
    priority: 68,
    status: "enabled",
    sort_order: 14,
  },
  {
    id: "local-15",
    template_code: "social_coop_decline",
    category_level_1: "社交",
    category_level_2: "合作邀约",
    title: "合作邀约不想接，怎么礼貌拒绝",
    short_desc: "拒绝合作但保留基本礼貌。",
    preset_input: "有人邀我合作，但我当前不想接这个项目。",
    recommended_tones: ["礼貌委婉", "温和留余地", "简短边界"],
    priority: 67,
    status: "enabled",
    sort_order: 15,
  },
  {
    id: "local-16",
    template_code: "stranger_train_seat",
    category_level_1: "陌生人",
    category_level_2: "换座",
    title: "高铁换座，怎么礼貌拒绝",
    short_desc: "礼貌拒绝不合理换座请求。",
    preset_input: "高铁上有人想和我换座，但我不想换。",
    recommended_tones: ["礼貌委婉", "简短边界", "坚定直接"],
    priority: 94,
    status: "enabled",
    sort_order: 16,
  },
  {
    id: "local-17",
    template_code: "stranger_rude_talk",
    category_level_1: "陌生人",
    category_level_2: "无礼搭话",
    title: "陌生人无礼搭话，怎么结束对话",
    short_desc: "冷静制止并快速退出互动。",
    preset_input: "陌生人一直无礼搭话，我想尽快结束对话。",
    recommended_tones: ["简短边界", "坚定直接", "礼貌委婉"],
    priority: 73,
    status: "enabled",
    sort_order: 17,
  },
  {
    id: "local-18",
    template_code: "stranger_bad_comment",
    category_level_1: "陌生人",
    category_level_2: "恶意评论",
    title: "陌生人的恶意评论，怎么冷静回",
    short_desc: "不升级冲突，强调结束互动。",
    preset_input: "陌生人对我有恶意评论，我想冷静回应并结束互动。",
    recommended_tones: ["简短边界", "坚定直接", "温和留余地"],
    priority: 66,
    status: "enabled",
    sort_order: 18,
  },
  {
    id: "local-19",
    template_code: "stranger_unreasonable_request",
    category_level_1: "陌生人",
    category_level_2: "不合理请求",
    title: "被要求插队或配合不合理请求，怎么拒绝",
    short_desc: "冷静拒绝，保护自身权益。",
    preset_input: "有人要求我插队或配合不合理请求，我想直接拒绝。",
    recommended_tones: ["坚定直接", "简短边界", "礼貌委婉"],
    priority: 71,
    status: "enabled",
    sort_order: 19,
  },
];
